# Site
name: 'Bloggingwithravi'
description: 'Welcome to BloggingwithRavi. I will take you on the fabulous world of exploration. Travel, culture, lifestyle. Eat, Pray, Love!'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/Ravijoshiji.github.io'
disqus: 'bloggingwithravi-1'
email: 'bloggingwithraviOO7@gmail.com'
mailchimp-list: 'https://bloggingwithravi.us4.list-manage.com/subscribe/post?u=6624b5372168533b3b46d0d01&amp;id=10671579f2'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
 # Google Analytics
google_analytics:  UA—143528900-5
  
  
authors:
    sal:
      name:           Ravi Joshi
      site:           https://bloggingwithravi.com
      avatar:         /assets/images/20201127_115441.ico
      bio:            "I enjoy taking some time from Job and publish Articles, work for free on projects that I can share with you for your personal and commercial use."
      email:          bloggingwithraviOO7@gmail.com
      twitter:        https://mobile.twitter.com/bloggingwthravi

#     jane:
      name:           Ravi Joshi
      site:           https://bloggingwithravi.com
      avatar:         /assets/images/20201127_115441.ico
      bio:           "I enjoy taking some time from Job and publish Articles, work for free on projects that I can share with you for your personal and commercial use."
      email:          bloggingwithraviOO7@gmail.com
      twitter:        https://mobile.twitter.com/bloggingwthravi 
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
